In [1]:
import numpy as np
import pandas as pd

### 3 things you can do with missing data:
### - Leave it as missing
#### * use this mostly with categorical data
### - Remove the missing data
#### * if you're missing a large percentage of data it's best to remove the column
#### * if you're missing a small percentage of data it's best to remove that row
### - Fill in the missing data
#### * if the missing data is important then replace it with a reasonable value

In [2]:
df = pd.DataFrame({
    'A': [1, 2, np.nan, 4],
    'B': [5, np.nan, np.nan, 8],
    'C': [10, 20, 30, 40]
})

In [3]:
df

     A    B   C
0  1.0  5.0  10
1  2.0  NaN  20
2  NaN  NaN  30
3  4.0  8.0  40

#### Remove the missing data:
.dropna()
##### you will get the rows where nothing is missing because the default value for axis is 0

In [4]:
df.dropna()

     A    B   C
0  1.0  5.0  10
3  4.0  8.0  40

#### if you set the axis to 1 you will get the cols where nothing is missing

In [5]:
df.dropna(axis=1)

    C
0  10
1  20
2  30
3  40

#### thresh determines how many NaN
##### - on the example below the threshhold is 3, so must have at least 2 NaN values

In [8]:
df.dropna(axis=1, thresh=3)

     A   C
0  1.0  10
1  2.0  20
2  NaN  30
3  4.0  40

##### - usually you calculate thresh based on a percentage
###### in example below we get back the cols with at least 75% of the values

In [9]:
thresh = 0.25 * len(df)
df.dropna(axis=1, thresh=thresh)

     A    B   C
0  1.0  5.0  10
1  2.0  NaN  20
2  NaN  NaN  30
3  4.0  8.0  40

#### Fill in the missing data

##### if the fill value is a different data type then the rest of the col values are converted to that data type.
###### on example below 1.0, 2.0, 4.0 5.0, 8.0 are now type string

In [10]:
df.fillna(value='FILL VALUE')

            A           B   C
0         1.0         5.0  10
1         2.0  FILL VALUE  20
2  FILL VALUE  FILL VALUE  30
3         4.0         8.0  40

In [11]:
df.fillna(value=0)

     A    B   C
0  1.0  5.0  10
1  2.0  0.0  20
2  0.0  0.0  30
3  4.0  8.0  40

#### You don't have to replace values in the entire df.

In [14]:
df['A'] = df['A'].fillna(value=0)

In [15]:
df

     A    B   C
0  1.0  5.0  10
1  2.0  NaN  20
2  0.0  NaN  30
3  4.0  8.0  40

#### Fill in the values in 'B' with the avridge values of non missing elements

In [17]:
df['B'].fillna(df['B'].mean())

0    5.0
1    6.5
2    6.5
3    8.0
Name: B, dtype: float64

In [18]:
df.fillna(df.mean())

     A    B   C
0  1.0  5.0  10
1  2.0  6.5  20
2  0.0  6.5  30
3  4.0  8.0  40