In [2]:
import numpy as np
import pandas as pd

In [3]:
columns = ['W', 'X', 'Y', 'Z']

In [4]:
index = ['A', 'B', 'C', 'D', 'E']

In [6]:
from numpy.random import randint

In [9]:
np.random.seed(42)
data = randint(-100, 100, (5, 4))

In [10]:
data

array([[  2,  79,  -8, -86],
       [  6, -29,  88, -80],
       [  2,  21, -26, -13],
       [ 16,  -1,   3,  51],
       [ 30,  49, -48, -99]], dtype=int32)

#### The pd.DataFrame() takes the data the index and the columns as params

In [11]:
df = pd.DataFrame(data, index, columns)

In [12]:
df

    W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

#### Getting a single column

In [14]:
df["W"]

A     2
B     6
C     2
D    16
E    30
Name: W, dtype: int32

#### Getting multiple columns by passing in a list of column names. The column names don't have to be in order

In [17]:
df[['Z', 'W']]

    Z   W
A -86   2
B -80   6
C -13   2
D  51  16
E -99  30

#### Create new column based on other columns (Feature Engineering)

In [33]:
df['new'] = df['W'] + df['Y']

In [34]:
df

    W   X   Y   Z  new
A   2  79  -8 -86   -6
B   6 -29  88 -80   94
C   2  21 -26 -13  -24
D  16  -1   3  51   19
E  30  49 -48 -99  -18

#### Removing a column. Axis 1 means look for the column. Axis 0 means look for the row. df.drop doesn't remove anything permanently. To keep the change you need to reassign.

In [35]:
df = df.drop('new', axis=1)

In [42]:
df

    W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

#### To locate a row use the method .loc, it returns the row as a series. To locate multiple rows pass in a list.

In [45]:
df.loc[['A', 'B']]

   W   X   Y   Z
A  2  79  -8 -86
B  6 -29  88 -80

#### To locate by int index location use .iloc

In [49]:
df.iloc[0:3]

   W   X   Y   Z
A  2  79  -8 -86
B  6 -29  88 -80
C  2  21 -26 -13

#### To drop a row pass in the name of the row, you don't need to specify the axis since the default axis is 0

In [50]:
df.drop('C')

    W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
D  16  -1   3  51
E  30  49 -48 -99

#### Select a subset of rows and cols at the same time. You pass in the row and then the column

In [54]:
df.loc[['A', 'C'], ['W', 'Y']]

   W   Y
A  2  -8
C  2 -26

In [55]:
df

    W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

## Conditional selection

#### df comparison operator returns a df of bool values

In [56]:
df > 0

      W      X      Y      Z
A  True   True  False  False
B  True  False   True  False
C  True   True  False  False
D  True  False   True   True
E  True   True  False  False

#### If you pass in the condition to the df it returns df where the values that don't meet the condition are removed

In [58]:
df[df > 0]

    W     X     Y     Z
A   2  79.0   NaN   NaN
B   6   NaN  88.0   NaN
C   2  21.0   NaN   NaN
D  16   NaN   3.0  51.0
E  30  49.0   NaN   NaN

In [60]:
df

    W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

In [61]:
df['X'] > 0

A     True
B    False
C     True
D    False
E     True
Name: X, dtype: bool

#### Returns only rows where 'X' is greater than 0

In [64]:
df[df['X'] > 0]

    W   X   Y   Z
A   2  79  -8 -86
C   2  21 -26 -13
E  30  49 -48 -99

#### You can select on multiple conditions. Operators:
##### & and
##### | or

In [65]:
df[(df['W']>0) & (df['Y']>1)]

    W   X   Y   Z
B   6 -29  88 -80
D  16  -1   3  51

#### Reset index to int values
##### .reset_index() creates int index col and converts old index col into a new col named index

In [67]:
df.reset_index()

  index   W   X   Y   Z
0     A   2  79  -8 -86
1     B   6 -29  88 -80
2     C   2  21 -26 -13
3     D  16  -1   3  51
4     E  30  49 -48 -99

#### Setting existing column as index

In [69]:
new_ind = ['CA', 'NY', 'WY', 'OR', 'CO']

In [70]:
df['States'] = new_ind

#### .set_index gets rid of the old index and replaces it with the column that is passed in.
##### !REMEMBER! the index column name is not the name of the column.
###### In the example below the columns are 'W', 'X', 'Y', 'Z' and 'States' is the name of the index

In [75]:
df = df.set_index('States')

In [76]:
df

         W   X   Y   Z
States
CA       2  79  -8 -86
NY       6 -29  88 -80
WY       2  21 -26 -13
OR      16  -1   3  51
CO      30  49 -48 -99

In [77]:
df.columns

Index(['W', 'X', 'Y', 'Z'], dtype='str')

#### .describe() returns statistical values

In [79]:
df.describe()

              W          X          Y          Z
count   5.00000   5.000000   5.000000   5.000000
mean   11.20000  23.800000   1.800000 -45.400000
std    11.96662  42.109381  51.915316  63.366395
min     2.00000 -29.000000 -48.000000 -99.000000
25%     2.00000  -1.000000 -26.000000 -86.000000
50%     6.00000  21.000000  -8.000000 -80.000000
75%    16.00000  49.000000   3.000000 -13.000000
max    30.00000  79.000000  88.000000  51.000000

#### .info() tells you how many non null values

In [80]:
df.info()

<class 'pandas.DataFrame'>
Index: 5 entries, CA to CO
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   W       5 non-null      int32
 1   X       5 non-null      int32
 2   Y       5 non-null      int32
 3   Z       5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes

#### .dtypes returns the data types

In [83]:
df.dtypes

W    int32
X    int32
Y    int32
Z    int32
dtype: object