In [1]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('example.csv')

In [7]:
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [10]:
df.to_csv('output.csv', index=True)

In [14]:
pd.read_csv('output.csv')

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15