In [2]:
import numpy as np
import pandas as pd

In [3]:
columns = ['W', 'X', 'Y', 'Z']

In [4]:
index = ['A', 'B', 'C', 'D', 'E']

In [6]:
from numpy.random import randint

In [9]:
np.random.seed(42)
data = randint(-100, 100, (5, 4))

In [10]:
data

array([[  2,  79,  -8, -86],
       [  6, -29,  88, -80],
       [  2,  21, -26, -13],
       [ 16,  -1,   3,  51],
       [ 30,  49, -48, -99]], dtype=int32)

#### The pd.DataFrame() takes the data the index and the columns as params

In [11]:
df = pd.DataFrame(data, index, columns)

In [12]:
df

    W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

#### Getting a single column

In [14]:
df["W"]

A     2
B     6
C     2
D    16
E    30
Name: W, dtype: int32

#### Getting multiple columns by passing in a list of column names. The column names don't have to be in order

In [17]:
df[['Z', 'W']]

    Z   W
A -86   2
B -80   6
C -13   2
D  51  16
E -99  30

#### Create new column based on other columns (Feature Engineering)

In [33]:
df['new'] = df['W'] + df['Y']

In [34]:
df

    W   X   Y   Z  new
A   2  79  -8 -86   -6
B   6 -29  88 -80   94
C   2  21 -26 -13  -24
D  16  -1   3  51   19
E  30  49 -48 -99  -18

#### Removing a column. Axis 1 means look for the column. Axis 0 means look for the row. df.drop doesn't remove anything permanently. To keep the change you need to reassign.

In [35]:
df = df.drop('new', axis=1)

In [42]:
df

    W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

#### To locate a row use the method .loc, it returns the row as a series. To locate multiple rows pass in a list.

In [45]:
df.loc[['A', 'B']]

   W   X   Y   Z
A  2  79  -8 -86
B  6 -29  88 -80

#### To locate by int index location use .iloc

In [49]:
df.iloc[0:3]

   W   X   Y   Z
A  2  79  -8 -86
B  6 -29  88 -80
C  2  21 -26 -13

#### To drop a row pass in the name of the row, you don't need to specify the axis since the default axis is 0

In [50]:
df.drop('C')

    W   X   Y   Z
A   2  79  -8 -86
B   6 -29  88 -80
D  16  -1   3  51
E  30  49 -48 -99

#### Select a subset of rows and cols at the same time. You pass in the row and then the column

In [54]:
df.loc[['A', 'C'], ['W', 'Y']]

   W   Y
A  2  -8
C  2 -26