In [1]:
import numpy as np
import pandas as pd

In [2]:
df_one = pd.DataFrame({'k1':['A','A','B','B','C','C'],
                      'col1':[100,200,300,300,400,500],
                      'col2':['NY','CA','WA','WA','AK','NV']})

In [3]:
df_one

  k1  col1 col2
0  A   100   NY
1  A   200   CA
2  B   300   WA
3  B   300   WA
4  C   400   AK
5  C   500   NV

#### Information on unique values
##### .unique() returns any unique values

In [4]:
df_one['col2'].unique()

<StringArray>
['NY', 'CA', 'WA', 'AK', 'NV']
Length: 5, dtype: str

##### .nunique() returns number of unique values

In [5]:
df_one['k1'].nunique()

3

##### .value_counts() returns counts per unique entry

In [7]:
df_one['col2'].value_counts()

col2
WA    2
NY    1
CA    1
AK    1
NV    1
Name: count, dtype: int64

##### .drop_duplicates() removes all duplicate values

In [8]:
df_one.drop_duplicates()

  k1  col1 col2
0  A   100   NY
1  A   200   CA
2  B   300   WA
4  C   400   AK
5  C   500   NV

#### Using functions to apply to all items
##### !Watch out for datatype errors!

In [10]:
def grab_first_letter(state):
    return state[0]

In [12]:
df_one['First letter'] = df_one['col2'].apply(grab_first_letter)

In [13]:
df_one

  k1  col1 col2   NEW First letter
0  A   100   NY  1000            N
1  A   200   CA  2000            C
2  B   300   WA  3000            W
3  B   300   WA  3000            W
4  C   400   AK  4000            A
5  C   500   NV  5000            N

In [14]:
def complex_letter(state):
    if state[0] == 'W':
        return "Washington"
    else:
        return "Error"

In [15]:
df_one['col2'].apply(complex_letter)

0         Error
1         Error
2    Washington
3    Washington
4         Error
5         Error
Name: col2, dtype: str

#### Create new column with mapping

In [16]:
df_one['k1']

0    A
1    A
2    B
3    B
4    C
5    C
Name: k1, dtype: str

In [17]:
my_map = {
    'A': 1,
    'B': 2,
    'C': 3
}

In [19]:
df_one['nums'] = df_one['k1'].map(my_map)

In [20]:
df_one

  k1  col1 col2   NEW First letter  nums
0  A   100   NY  1000            N     1
1  A   200   CA  2000            C     1
2  B   300   WA  3000            W     2
3  B   300   WA  3000            W     2
4  C   400   AK  4000            A     3
5  C   500   NV  5000            N     3

#### Locate index of max and min values

In [21]:
df_one

  k1  col1 col2   NEW First letter  nums
0  A   100   NY  1000            N     1
1  A   200   CA  2000            C     1
2  B   300   WA  3000            W     2
3  B   300   WA  3000            W     2
4  C   400   AK  4000            A     3
5  C   500   NV  5000            N     3

In [24]:
df_one['col1'].idxmax()

5

In [25]:
df_one['col1'].idxmin()

0

#### Get column names

In [26]:
df_one.columns

Index(['k1', 'col1', 'col2', 'NEW', 'First letter', 'nums'], dtype='str')

#### Reasign column names, this effect IS permanent

In [27]:
df_one.columns = ['C1', 'C2', 'C3', 'C4', 'C5', 'C6']

In [28]:
df_one

  C1   C2  C3    C4 C5  C6
0  A  100  NY  1000  N   1
1  A  200  CA  2000  C   1
2  B  300  WA  3000  W   2
3  B  300  WA  3000  W   2
4  C  400  AK  4000  A   3
5  C  500  NV  5000  N   3

#### Sort values, in example below because C3 is alphabetical it sorts alphabetically, but index stays the same

In [31]:
df_one.sort_values('C3', ascending=False)

  C1   C2  C3    C4 C5  C6
2  B  300  WA  3000  W   2
3  B  300  WA  3000  W   2
0  A  100  NY  1000  N   1
5  C  500  NV  5000  N   3
1  A  200  CA  2000  C   1
4  C  400  AK  4000  A   3

### Dummy variable features

In [37]:
features = pd.DataFrame({
    'A': [100, 200, 300, 400, 500],
    'B': [12, 13, 14, 15, 16],
})
predictions = pd.DataFrame({'pred': [0, 1, 1, 0, 1]})

In [38]:
features

     A   B
0  100  12
1  200  13
2  300  14
3  400  15
4  500  16

In [39]:
predictions

   pred
0     0
1     1
2     1
3     0
4     1

#### Concat two dataframes.
##### By default it concatinates along the rows. To concat along the columns set axis to 1

In [40]:
pd.concat([features, predictions])

       A     B  pred
0  100.0  12.0   NaN
1  200.0  13.0   NaN
2  300.0  14.0   NaN
3  400.0  15.0   NaN
4  500.0  16.0   NaN
0    NaN   NaN   0.0
1    NaN   NaN   1.0
2    NaN   NaN   1.0
3    NaN   NaN   0.0
4    NaN   NaN   1.0

In [41]:
pd.concat([features, predictions], axis=1)

     A   B  pred
0  100  12     0
1  200  13     1
2  300  14     1
3  400  15     0
4  500  16     1

#### Create dummy variables

In [43]:
df_one['C1']

0    A
1    A
2    B
3    B
4    C
5    C
Name: C1, dtype: str

In [45]:
pd.get_dummies(df_one['C1'], dtype=int)

   A  B  C
0  1  0  0
1  1  0  0
2  0  1  0
3  0  1  0
4  0  0  1
5  0  0  1